// Code generated from contracts/gallery.schema.json. DO NOT EDIT.
package gallery

var schemaNames = map[string]string{
	"catalog":               "catalog",
	"publicImage":           "image",
	"artwork":               "artwork",
	"offer":                 "offer",
	"offeredFile":           "offeredFile",
	"collection":            "collection",
	"exhibit":               "exhibit",
	"section":               "section",
	"draft":                 "draft",
	"asset":                 "asset",
	"apiError":              "error",
	"assetPage":             "assetPage",
	"readiness":             "readiness",
	"orderInput":            "orderInput",
	"orderItem":             "orderItem",
	"orderView":             "order",
	"orderCreation":         "orderCreation",
	"entitlement":           "entitlement",
	"downloadLinkInput":     "downloadInput",
	"download":              "download",
	"downloadCreation":      "downloadCreation",
	"accessReissueInput":    "accessReissueInput",
	"accessReissue":         "accessReissue",
	"accessReissueCreation": "accessReissueCreation",
	"ownerOrderSummary":     "ownerOrder",
	"ownerOrderPage":        "ownerOrderPage",
	"orderUpdate":           "orderUpdate",
	"receiptView":           "receipt",
	"publicationRequest":    "publicationRequest",
	"publication":           "publication",
	"orderSnapshot":         "orderSnapshot",
	"emptyInput":            "emptyInput",
}
